version: '3.9'
services:
  web:
    image: node-web-app
    build: .
    ports:
      - '3000:3000'
    command: 'node index.js'
    depends_on:
      - 'mongo'
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /database:/data/db
